"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ParamDecoratorType;
(function (ParamDecoratorType) {
    ParamDecoratorType["User"] = "User";
    ParamDecoratorType["Body"] = "Body";
    ParamDecoratorType["BodyField"] = "BodyField";
    ParamDecoratorType["Header"] = "Headers";
    ParamDecoratorType["HeaderField"] = "HeaderField";
    ParamDecoratorType["Query"] = "Query";
    ParamDecoratorType["QueryField"] = "QueryField";
    ParamDecoratorType["Request"] = "Request";
    ParamDecoratorType["RawRequest"] = "RawRequest";
    ParamDecoratorType["ContainerInject"] = "ContainerInject";
    ParamDecoratorType["Connection"] = "Connection";
    ParamDecoratorType["Broker"] = "Broker";
    ParamDecoratorType["Method"] = "Method";
    ParamDecoratorType["Params"] = "Params";
    ParamDecoratorType["ParamField"] = "ParamField";
})(ParamDecoratorType = exports.ParamDecoratorType || (exports.ParamDecoratorType = {}));
